### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Odianosen25** [Kong/unirest-python#43]
Hello,

I am running on python 3.6 and after installing it, I run `import unirest` and get the following errors:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\EOdianosen\AppData\Local\Programs\Python\Python36-32\lib\site-packages\unirest\__init__.py", line 98
    except urllib2.HTTPError, e:
                            ^
SyntaxError: invalid syntax
```
Please any thing I might be missing?

Thanks

**Comment by tirkarthi** [comment]
This is due to the syntax being invalid in Python 3. I have made a fork compatible with Python 3 at https://github.com/tirkarthi/unirest-python . You can use it as a git based dependency.
